-- HEADER
SELECT
	DISTINCT 
	VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE AS DYELOT,
	VIEWPRODUCTIONRESERVATION.GROUPLINE AS REDYE,
	'1410' AS MACHINE,
	0 AS TYPEOFPROCEDURE,
	0 AS PROCEDURENO,
	0 AS COLOR,
	TRIM(VIEWPRODUCTIONRESERVATION.SUBCODE01) || '-' || TRIM(VIEWPRODUCTIONRESERVATION.SUFFIXCODE) AS RECIPENO,
	i.PROJECTCODE AS ORDERNO,
	i.ORDPRNCUSTOMERSUPPLIERCODE AS CUSTOMER,
	'' AS ARTICLE,
	SUBSTR(TRIM(VIEWPRODUCTIONRESERVATION.SUBCODE01), 7, 7) AS COLORNO,
	ir.INITIALUSERPRIMARYQUANTITY AS WEIGHT,
	0 AS LENGHT,
	VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY AS LIQUORATIO,
	0 AS LIQUORQUANTITY,
	0 AS PUMPSPEED,
	0 AS REELSPEED,
	0 AS ABSORPTION
FROM
	VIEWPRODUCTIONRESERVATION VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWKK i ON i.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE
LEFT JOIN ITXVIEW_RESERVATION ir ON ir.PRODRESERVATIONLINKGROUPCODE = VIEWPRODUCTIONRESERVATION.PRODRESERVATIONLINKGROUPCODE 
								AND ir.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE 
WHERE
	VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00171082'
	AND VIEWPRODUCTIONRESERVATION.GROUPLINE = '625'



-- DETAIL
SELECT
	CASE
		WHEN ITXVIEWRESEP.CODE = '' THEN ITXVIEWRESEP2.CODE
		ELSE ITXVIEWRESEP.CODE
	END	AS CODE,
	CASE
		WHEN ITXVIEWRESEP.SUBCODE = '' THEN ITXVIEWRESEP2.SUBCODE
		ELSE ITXVIEWRESEP.SUBCODE
	END	AS SUBCODE,
	CASE
		WHEN ITXVIEWRESEP.CONSUMPTION IS NULL OR ITXVIEWRESEP.CONSUMPTION = 0 THEN ITXVIEWRESEP2.CONSUMPTION
		ELSE ITXVIEWRESEP.CONSUMPTION
	END	AS CONSUMPTION,
	CASE
		WHEN ITXVIEWRESEP.COMMENTLINE IS NULL OR ITXVIEWRESEP.COMMENTLINE = '' THEN ITXVIEWRESEP2.COMMENTLINE
		ELSE ITXVIEWRESEP.COMMENTLINE
	END	AS CONSUMPTION,
	CASE
		WHEN ITXVIEWRESEP.LONGDESCRIPTION IS NULL OR ITXVIEWRESEP.LONGDESCRIPTION = '' THEN ITXVIEWRESEP2.LONGDESCRIPTION
		ELSE ITXVIEWRESEP.LONGDESCRIPTION
	END	AS CONSUMPTION,
	CASE
		WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
		ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
	END	AS CONSUMPTION
FROM
	VIEWPRODUCTIONRESERVATION VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWRESEP ITXVIEWRESEP ON VIEWPRODUCTIONRESERVATION.SUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE_RESERVATION
	AND VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = ITXVIEWRESEP.PRODUCTIONORDERCODE
	AND VIEWPRODUCTIONRESERVATION.SUBCODE01 = ITXVIEWRESEP.SUBCODE01_RESERVATION
	AND VIEWPRODUCTIONRESERVATION.COMPANYCODE = ITXVIEWRESEP.COMPANYCODE
LEFT JOIN ITXVIEWRESEP2 ITXVIEWRESEP2 ON ITXVIEWRESEP2.RECIPESUBCODE01 = ITXVIEWRESEP.CODE AND ITXVIEWRESEP2.RECIPESUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE
WHERE 
	VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00171082'
	AND VIEWPRODUCTIONRESERVATION.GROUPLINE = '625'
ORDER BY
	ITXVIEWRESEP.GROUPNUMBER,
	ITXVIEWRESEP.SEQUENCE,
	ITXVIEWRESEP2.GROUPNUMBER,
	ITXVIEWRESEP2.SEQUENCE ASC